// ############################# 1 ###############################


/*

const p2 = document.querySelector("#p2");
console.log(p2);

const ps = document.getElementsByTagName("p")
        for (const p of ps) {
            console.log(p)
        }   

const psContents = document.getElementsByTagName("p");
for (const p of psContents){
console.log(p.innerHTML)
}

const red = document.getElementsByClassName("red")
for (elm of red) {
    console.log(elm)
}

*/

// ############################# 2 ###############################

/*
let sol = document.getElementById("p1");
sol.innerHTML = "Está um dia de chuva"


let imagem = document.querySelector("img")
imagem.src = "https://www.altominho.tv/site/wp-content/uploads/2019/02/chuva.jpg"

let p2 = document.getElementById("p2");
p2.style.backgroundColor = "yellow";
*/


// ############################# 3 ###############################
/*
document.body.innerHTML +=  `<table>
<tr>
    <th>Escola</th>
    <th>Local</th>
</tr>
<tr>
    <td>ESMAD</td>
    <td>Vila do Conde</td>
</tr>
</table>
`
*/

// ############################# 4 ###############################

// document.getElementById("but").onclick = function(){

   // alert("Olá Mundo!") 
// }






